package com.spilab.alberto.karabella.scrapper;

import android.util.Log;
import android.view.accessibility.AccessibilityEvent;

import com.spilab.alberto.karabella.manager.WhatsappManager;
import com.spilab.alberto.karabella.model.WhatsappDB;
import com.spilab.alberto.karabella.utils.EventDataExtractor;
import com.spilab.alberto.karabella.utils.Strings;

import java.util.List;

/**
 * Created by alberto on 18/10/17.
 *
 * Whatsapp scrapper, this class scraps and puts in a POJO the whatsapp user interaction
 */

public class WhatsappScrapper {

    private static final String TAG = "WhatsappScrapper";

    /** WhatsappDB model */
    private WhatsappDB whatsappDB;

    /** String data, stores what the user is writting in real time */
    private String data = "";

    /** Boolean to prevent the double entry in whatsapp home generated by events */
    private boolean doubleTry = false;

    /** Boolean to control if the user is erasing what is writting */
    private boolean erasing = false;

    private String interlocutor = "";

    public void getData(AccessibilityEvent event, String timestamp){

        if(whatsappDB == null) // If the whatsapp manager is null, instantiate it
            whatsappDB = new WhatsappDB();


        switch (event.getClassName().toString()){

            case Strings.CLASS_HOMEACTIVITY:

                // Saves the previous whatsappDB object (if exists) in database
                storeObjectInRealm(timestamp);

                if(!doubleTry){
                    doubleTry = true;
                }else {
                    Log.d(TAG, "Navigate to whatsapp home");

                    // TODO remove ----
                    List<WhatsappDB> whatsappDBList = WhatsappManager.getAllWhatsappModels();
                    for (WhatsappDB wdb : whatsappDBList) {
                        Log.d("Whatsapp stored content", wdb.toString());
                    }
                    // TODO remove ~~~~

                    // Create a new instance of whatsappDB model
                    whatsappDB = new WhatsappDB();

                    // Set the start timestamp to this model
                    whatsappDB.setTimestampStart(timestamp);

                    doubleTry = false;
                }
                break;

            case Strings.WIDGET_RELATIVE_LAYOUT: //Clicked whatsapp conversation

                // Extract the contact name string
                interlocutor = this.getContactName(EventDataExtractor.getEventText(event));
                whatsappDB.setInterlocutor(interlocutor);

                Log.d(TAG, "Clicked whatsapp conversation: " + interlocutor);
                break;

            case Strings.WIDGET_EDITTEXT: /* Writting in whatsapp conversation */

                // Check that the eventText is not "Escribir mensaje"
                if(EventDataExtractor.getEventText(event).equals("Escribir mensaje") || event.getText() == null || event.getBeforeText() == null)
                    return;


                /* Checks if the user is erasing the line or what the fuck */
                if(event.getBeforeText().length() > EventDataExtractor.getEventText(event).length()){
                    erasing = true;
                }else{
                    erasing = false;
                }

                /* Stores the written string */
                data = EventDataExtractor.getEventText(event);

                /* New non erasing string */
                if((data.length() == 1) && !erasing){
                    Log.d("New line: ", data);
                    addNewLine(data, timestamp);
                }else {

                    /* Feeding the actual string */
                    if(!erasing) {
                        Log.d("Current: ", data);
                        addCurrentLine(data, timestamp);
                    }
                }
                break;

            default:
                EventDataExtractor.printEvent(event);
                break;
        }
    }

    private void addNewLine(String data, String timestamp){
        /* If the interlocutor is not set */
        if(whatsappDB.getInterlocutor().isEmpty())
            whatsappDB.setInterlocutor(this.interlocutor);

        whatsappDB.addNewTextRegistry(data, timestamp);

    }

    private void addCurrentLine(String data, String timestamp){
         /* If the interlocutor is not set */
        if(whatsappDB.getInterlocutor().isEmpty())
            whatsappDB.setInterlocutor(this.interlocutor);

        whatsappDB.addTextToRegistry(data, timestamp);
    }

    /**
     * getContactName, method that extracts the name of the person or group that the user is writing on
     * @param eventText, accessibilityEvent text.
     * @return String contactName, the extracted name
     * */
    private String getContactName(String eventText){

        String contactName = "";
        for(int i = 0; i < eventText.length(); i++){
            if(eventText.charAt(0) == eventText.charAt(i)){
                contactName = eventText.substring(0, i);
            }
        }
        return contactName;
    }

    /**
     * checkUserInput, checks if there is any existing content in the data string
     * that must be saved
     *
     * This method is called when the user navigates to Whatsapp Home or when there is any
     * change of context in the screen (new activities loaded...etc).
     */
    public void addUserInput(String timestamp){

        if(this.data.length() > 1){ //There is a non-erasing string
            Log.d("CheckUserInput: ", data);
            whatsappDB.addTextToRegistry(data, timestamp);
            data = ""; // Reset the stored string
        }else{
            Log.d(TAG, "CheckUserInput: No hay data");
        }
    }

    /**
     * sotreObjectInRealm, method that calls WhatsappManager to
     * save or update the WhatsappDB model.
     * @param timestamp String describing the time when the user abandoned the conversation
     */
    public void storeObjectInRealm(String timestamp){

        if(this.whatsappDB != null && this.whatsappDB.getInterlocutor() != null) {
          //  if(this.whatsappDB.getLastTextRegistry().length() != 0){ // There is some data to store
                this.whatsappDB.setTimestampEnd(timestamp);
                WhatsappManager.saveOrUpdateWhatsappDB(this.whatsappDB);
            //}

        }
    }

    public void contextChange(String timestamp){
        Log.d(TAG, "Comprobando el cambio de contexto desde whatsapp");
        if(this.whatsappDB == null || this.whatsappDB.getTextList() == null) //If whatsappDB object is empty
            return;

        if(this.data.length() > 1){ //There is a non-erasing string
            Log.d("contextChange: ", data);
            whatsappDB.addNewTextRegistry(data, timestamp);
            storeObjectInRealm(timestamp);
        }else{
            Log.d(TAG, "CheckUserInput: No hay data");
        }
    }


}
